### ISSUE TITLE
Wrong Format Exception

### ISSUE THREAD

**Issue by selifan** [bosonbeard/ML_-spectrum_classification#1]
При запуске приложения в моей конфигурации вылезало исключение System.FormatException,
как выяснилось - из-за того, что дефолтный разделитель для десятичных знаков у меня запятая, а в строках файлов данных - привычные точки (будь там запятые , парсинг CSV вообще не прошел бы как надо, т.к. запятые - разделители между числами).
Возможно, стоит в исходник добавить принудительную смену дес. разделителя ДО первого вызова ToJagged():

            System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
            customCulture.NumberFormat.NumberDecimalSeparator = ".";
            System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;

После этого тест заработал на "Ура".

**Comment by bosonbeard** [comment]
Если будет время вставлю, в проекте .net  должны были лежать данные с корректным разделителем.

**Comment by bosonbeard** [comment]
Добавил Ваш код, также заменил данные в .net проекте на разделенные точкой. (десятичной части)
Если хотите проверьте.
